### PR TITLE
General codebase update

### PR DESCRIPTION
**Pull request by cyb3rko**
I did the following things by updating the codebase and being able to build the app again:

- Update to AndroidX
- Replacing non existing Stargazers library with [AppRate library](https://github.com/Vorlonsoft/AndroidRate)
- Target Sdk Version to 31
- reformat code

Fabric was deprecated, so this app would have to upgrade to Firebase Crashlytics and Analytics.
You have to add the app to a new Firebase Project and add the config to this app, I can not do this.
I added TODO notes which parts of the code have to be updated with Crashlytics / Analytics.

The Material Dialog library could not be updated because the version this app uses is the last one which is compatible with Java.
Do you plan on rewriting this app to Kotlin? I could try to do this as well.

Furthermore we could remove the whole Parse package and replace it with the official Android SDK for parse.
Shall we do it?

### CODE REVIEW

**Comment by bitterbit** [comment]
Looks good! I need to install Android development environment so I can check all is good and then I'll approve this PR :)

**Comment by cyb3rko** [comment]
Alright.
What about the other things?
Do you want to replace the deprecated Fabric Api?
Do you want to rewrite it to Kotlin?
Do you want to replace your 'Parse' package with the official Android SDK?

**Comment by bitterbit** [comment]
_Do you want to replace the deprecated Fabric Api?_
Yes lets remove it 

_Do you want to rewrite it to Kotlin?_
I don't have the capacity to do it but if you want to take it on that would be cool, is it possible to convert only a few files to Kotlin? I never wrote code in Kotlin so I am not sure how it works

_Do you want to replace your 'Parse' package with the official Android SDK?_
If I remember correctly I patched something in 'Parse', updating to a new version is a good idea but it might not be simple. I would love to merge a 'Parse' version update if you will make one

**Comment by cyb3rko** [comment]
> _Do you want to replace the deprecated Fabric Api?_
> Yes lets remove it

Ok, so I just remove it WITHOUT replacing with Firebase services (Crashlytics, Analytics)?

> _Do you want to rewrite it to Kotlin?_
> I don't have the capacity to do it but if you want to take it on that would be cool, is it possible to convert only a few files to Kotlin? I never wrote code in Kotlin so I am not sure how it works

Yeah, you can write only a few files in Kotlin. Kotlin and Java are compatible.
I can start rewriting the files to Kotlin, of course.

> _Do you want to replace your 'Parse' package with the official Android SDK?_
> If I remember correctly I patched something in 'Parse', updating to a new version is a good idea but it might not be simple. I would love to merge a 'Parse' version update if you will make one

I will take a look if I can do what you did with your custom adaption. Maybe the updates of the last years have the features you added, let's see.

**Comment by cyb3rko** [comment]
I've finished rewriting the app to Kotlin, but there is a problem accessing the LazyList class.
Most probably I just have to update it too and it will be good to go.

While updating https://github.com/bitterbit/LazyParse I've come around the MainApplication.java file with the following content:

```
Parse.initialize(new Parse.Configuration.Builder(this)
        .server(getString(R.string.server))
        .applicationId(getString(R.string.application_id))
        .clientKey(getString(R.string.client_key))
        .build()
);
```

But these strings do not exist in the project, the strings.xml file is the following:

```
<resources>
    <string name="app_name">LazyParse</string>
</resources>
```

So my question now is if the sample app shall be working (has ever worked) or is it just code which has to be filled by the developers?

**Comment by bitterbit** [comment]
Nice! 
Regarding the last question, I used to have it configured to my own parse server and didn't want to expose the credentials publicly. It should work by adding the correct values in strings.xml

**Comment by cyb3rko** [comment]
Ok, I'm going to add dummy values to prevent the errors.

**Comment by cyb3rko** [comment]
I've finished school so now I have some more time to work on this project.
But I can't get LazyParse to be built successfully via Jitpack.

The build is working but if you import it into any project, the classes (LazyList, LazyParseObjectHolder, ...) are just not accessible.

I don't get it. Any idea?

**Comment by bitterbit** [comment]
Hi! how have you been? :) 
I am not sure what happened to it, it might just be that jitpack removed it after inactivity or something. 
Anyway the source is available here: https://github.com/bitterbit/LazyParse 

Let me know if I can help you with this

**Comment by cyb3rko** [comment]
I REALLY want to make this app awesome with modern design and cool features (those from the iOS App and more), as my main project depends on Parse-Server.

But I could not work on it for now because of the outdated dependencies. I upgraded them but as mentioned Jitpack does not build it correctly.

So now I will do the following:

- completely renew LazyParse: I saw you copied all the Android SDK classes into the library to adapt them, but many of them are outdated compared to current releases, so I try to build it from scratch (but following the LazyParse you built before)
- once finished I will try to implement it into the Dashboard app; it it still fails via Jitpack I will implement a .jar file for LazyParse for development. If everything's finished I can take a look if I can get LazyParse on Jitpack to work again.
- If I will have successfully included LazyParse into the Dashboard I will make a pull request.

- Second step would be renewing the design according to modern design guidelines.
- The last step then is to develop new features, if everything works as expected.

And maybe in the end we have a renewed and awesome Android dashboard app 😍

**Comment by bitterbit** [comment]
Woohooo sounds amazing, good luck!

**Pull request merged**
